# -*- coding: utf-8 -*-
"""HeartRateClassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dqcZ2ebJFnjA35SYAW1vE1MF-HUIEYQP
"""

age = int(input("Please enter your age (required). This will be used to calculate your max heart rate. "))
workout_mode = int(input("Please enter the workout mode (optional). You can choose from recovery [1], endurance [2], moderate [3], sprint [4], and interval [5]. "))

class Range():
  def __init__(self, workout_mode: int):
    self.mode = workout_mode
    self.range = self.to_range(self.mode)

  def to_range(self, workout_mode):
    if workout_mode == 1:
      return (50, 60)
    if workout_mode == 2:
      return (60, 70)
    if workout_mode == 3:
      return (70, 80)
    if workout_mode == 4:
      return (80, 90)
    if workout_mode == 5:
      return (90, 100)

  def is_inside(self, heart_rate) -> bool:
    if heart_rate > self.range[0] and heart_rate <= self.range[1]: # inclusive is arbitrary
      return True
    return False

def check_range(age, heart_rate, workout_mode):
  max_heart_rate = 220 - age # bpm units
  range = Range(workout_mode)
  if range.is_inside(heart_rate):
    return True
  return False

heart_rate = int(input("Enter heart rate (this will be inputted from sensors later):"))
check_range(age, heart_rate, workout_mode)